FROM node:latest as base

ENV environment dev

# Disable apt-get warnings
# https://github.com/wv-gis/mudak-wrm-public/issues/2
ENV APT_KEY_DONT_WARN_ON_DANGEROUS_USAGE=DontWarn

# Resolve apt-utils warning
# https://github.com/phusion/baseimage-docker/issues/319#issuecomment-245857919
# https://stackoverflow.com/questions/51023312/docker-having-issues-installing-apt-utils
ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -yq --no-install-recommends apt-utils

# Install EOL change utility
RUN apt-get update && apt-get install -yq dos2unix

# Install chrome for protractor tests
RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - &&\
  sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list' &&\
  apt-get update &&\
  apt-get install -yq google-chrome-stable

RUN apt-cache policy google-chrome-stable  
  
FROM base as build

RUN mkdir /usr/src/app && chown node:node /usr/src/app
WORKDIR /usr/src/app

ENV PATH /usr/src/app/node_modules/.bin:$PATH

COPY package.json package-lock.json ./
RUN npm install
COPY . .

FROM build as e2e-pre-release
RUN npm run build

FROM nginx:latest as e2e-release

RUN rm -rf /usr/share/nginx/html/*
COPY --from=e2e-pre-release /usr/src/app/dist/wordki /usr/share/nginx/html
COPY ./nginx.conf /etc/nginx/nginx.conf

ENTRYPOINT nginx -g 'daemon off;' "$@"
